process.loadEnvFile?.('.env');

module.exports = {
  apps: [
    {
      name: 'nebulastreams',
      script: 'index.js',
      instances: 2,
      exec_mode: 'cluster',
      time: true,
      max_memory_restart: '700M',
      exp_backoff_restart_delay: 2000,
      kill_timeout: 10000,
      listen_timeout: 10000,
      merge_logs: true,
      env: {
        NODE_ENV: 'production',
        PORT: '3000',
        PUBLIC_BASE_URL: 'https://nebula.work.gd',
        SMTP_HOST: process.env.SMTP_HOST || '',
        SMTP_PORT: process.env.SMTP_PORT || '587',
        SMTP_SECURE: process.env.SMTP_SECURE || 'false',
        SMTP_USER: process.env.SMTP_USER || '',
        SMTP_PASS: process.env.SMTP_PASS || '',
        SMTP_FROM: process.env.SMTP_FROM || '',
        SMTP_USER_2: process.env.SMTP_USER_2 || '',
        SMTP_PASS_2: process.env.SMTP_PASS_2 || '',
        SMTP_FROM_2: process.env.SMTP_FROM_2 || '',
        SMTP_USER_3: process.env.SMTP_USER_3 || '',
        SMTP_PASS_3: process.env.SMTP_PASS_3 || '',
        SMTP_FROM_3: process.env.SMTP_FROM_3 || '',
        SMTP_USER_4: process.env.SMTP_USER_4 || '',
        SMTP_PASS_4: process.env.SMTP_PASS_4 || '',
        SMTP_FROM_4: process.env.SMTP_FROM_4 || '',
        SUPPORTER_EMAIL_REPLY_TO: process.env.SUPPORTER_EMAIL_REPLY_TO || '',
        MEMORY_GUARD_ENABLED: 'true',
        MEMORY_GUARD_PRESSURE_PERCENT: '72',
        MEMORY_GUARD_CRITICAL_PERCENT: '84',
        MEMORY_GUARD_RESTART_PERCENT: '95',
        STREAMED_SPORTS_CHROME_PATH: '/home/ubuntu/.cache/puppeteer/chrome-headless-shell/linux-150.0.7871.24/chrome-headless-shell-linux64/chrome-headless-shell',
        STREAMED_SPORTS_BROWSER_TIMEOUT_MS: '15000',
        STREAMED_SPORTS_HLS_CACHE_MS: '60000',
        STREAMED_SPORTS_BROWSER_IDLE_MS: '120000',
        STREAMED_SPORTS_HLS_PROBE_ENABLED: 'true',
        STREAMED_SPORTS_HLS_BROWSER_FALLBACK_ENABLED: 'true',
        NEBULA_SPORTS_WC_XTREAM_BASE_URL: process.env.NEBULA_SPORTS_WC_XTREAM_BASE_URL || '',
        NEBULA_SPORTS_WC_XTREAM_USERNAME: process.env.NEBULA_SPORTS_WC_XTREAM_USERNAME || '',
        NEBULA_SPORTS_WC_XTREAM_PASSWORD: process.env.NEBULA_SPORTS_WC_XTREAM_PASSWORD || '',
        NEBULA_SPORTS_WC_XTREAM_CATEGORY_ID: process.env.NEBULA_SPORTS_WC_XTREAM_CATEGORY_ID || '105',
        SPORTSRC_API_KEY: process.env.SPORTSRC_API_KEY || '',
        WATCH_TOGETHER_CBOX_URL: 'https://www5.cbox.ws/box/?boxid=963947&boxtag=kceLWF',
        API_FOOTBALL_KEY: process.env.API_FOOTBALL_KEY || '',
        SCRAPLING_SERVICE_AUTOSTART: 'false',
        PROVIDER_GLOBAL_MAX_INFLIGHT: '3',
        PROVIDER_MAX_CONCURRENCY: '1',
        PROVIDER_HOST_MAX_INFLIGHT: '1',
        PROVIDER_FETCH_REQUEST_TIMEOUT_MS: '6000',
        PROVIDER_MAINTENANCE_INTERVAL_SECONDS: '300',
        STREMIO_FAST_PROVIDER_CONCURRENCY: '1',
        STREMIO_FAST_PROVIDER_LIMIT: '6',
        STREMIO_FAST_STREAM_LIMIT: '24',
        STREMIO_FAST_EARLY_RETURN_STREAMS: '1',
        STREMIO_FAST_MIN_COMPLETED_PROVIDERS: '1',
        STREMIO_FAST_MAX_WAIT_MS: '5000',
        STREMIO_QUALITY_GRACE_MS: '500',
        STREMIO_PREMIUM_PROVIDER_MIN_WAIT_MS: '1000',
        STREMIO_STREAM_OVERALL_TIMEOUT_MS: '6000',
        STREMIO_MAX_INFLIGHT_SEARCHES: '2',
        STREMIO_INFLIGHT_SLOT_WAIT_MS: '500',
        STREMIO_BACKGROUND_REFRESH_CONCURRENCY: '0',
        STREMIO_BACKGROUND_REFRESH_QUEUE_MAX: '0',
        STREMIO_BACKGROUND_REFRESH_MAX_INFLIGHT_SEARCHES: '1',
        STREMIO_BACKGROUND_REFRESH_MAX_PROVIDER_EXECUTIONS: '1',
        NUVIO_MAX_PLUGIN_EXECUTIONS: '0',
        NUVIO_PLUGIN_CONCURRENCY: '2',
        NUVIO_2_PLUGIN_CONCURRENCY: '2',
        STREAM_RESULT_EXTERNAL_CACHE_ENABLED: 'false',
        INCLUDE_LIVE_CATALOGS: 'false',
        VERBOSE_INFO_LOGS: 'false'
      }
    }
  ]
};
