module.exports = {
  apps: [
    {
      name: 'nebulastreams',
      script: 'index.js',
      instances: 2,
      exec_mode: 'cluster',
      time: true,
      max_memory_restart: '700M',
      exp_backoff_restart_delay: 2000,
      kill_timeout: 10000,
      listen_timeout: 10000,
      merge_logs: true,
      env: {
        NODE_ENV: 'production',
        PORT: '3000',
        PUBLIC_BASE_URL: 'https://nebula.work.gd',
        MEMORY_GUARD_ENABLED: 'true',
        MEMORY_GUARD_PRESSURE_PERCENT: '72',
        MEMORY_GUARD_CRITICAL_PERCENT: '84',
        MEMORY_GUARD_RESTART_PERCENT: '95',
        STREAMED_SPORTS_CHROME_PATH: '/tmp/puppeteer-browsers/chrome/linux-149.0.7827.55/chrome-linux64/chrome',
        STREAMED_SPORTS_BROWSER_TIMEOUT_MS: '15000',
        STREAMED_SPORTS_HLS_CACHE_MS: '0',
        STREAMED_SPORTS_BROWSER_IDLE_MS: '10000',
        STREAMED_SPORTS_HLS_PROBE_ENABLED: 'true',
        STREAMED_SPORTS_HLS_BROWSER_FALLBACK_ENABLED: 'false',
        API_FOOTBALL_KEY: process.env.API_FOOTBALL_KEY || '',
        SCRAPLING_SERVICE_AUTOSTART: 'false',
        PROVIDER_GLOBAL_MAX_INFLIGHT: '16',
        PROVIDER_MAX_CONCURRENCY: '4',
        PROVIDER_HOST_MAX_INFLIGHT: '3',
        PROVIDER_FETCH_REQUEST_TIMEOUT_MS: '18000',
        PROVIDER_MAINTENANCE_INTERVAL_SECONDS: '300',
        STREMIO_FAST_PROVIDER_CONCURRENCY: '5',
        STREMIO_FAST_PROVIDER_LIMIT: '50',
        STREMIO_FAST_STREAM_LIMIT: '100',
        STREMIO_FAST_EARLY_RETURN_STREAMS: '3',
        STREMIO_FAST_MIN_COMPLETED_PROVIDERS: '3',
        STREMIO_FAST_MAX_WAIT_MS: '13000',
        STREMIO_QUALITY_GRACE_MS: '3000',
        STREMIO_PREMIUM_PROVIDER_MIN_WAIT_MS: '6500',
        STREMIO_STREAM_OVERALL_TIMEOUT_MS: '19000',
        STREMIO_MAX_INFLIGHT_SEARCHES: '40',
        STREMIO_INFLIGHT_SLOT_WAIT_MS: '8000',
        STREMIO_BACKGROUND_REFRESH_CONCURRENCY: '2',
        STREMIO_BACKGROUND_REFRESH_QUEUE_MAX: '100',
        STREMIO_BACKGROUND_REFRESH_MAX_INFLIGHT_SEARCHES: '20',
        STREMIO_BACKGROUND_REFRESH_MAX_PROVIDER_EXECUTIONS: '8',
        NUVIO_MAX_PLUGIN_EXECUTIONS: '0',
        NUVIO_PLUGIN_CONCURRENCY: '6',
        NUVIO_2_PLUGIN_CONCURRENCY: '8',
        STREAM_RESULT_EXTERNAL_CACHE_ENABLED: 'false',
        INCLUDE_LIVE_CATALOGS: 'false',
        VERBOSE_INFO_LOGS: 'false'
      }
    }
  ]
};
